branch-defaults:
  main:
    environment: django-scraper-env-mumbai
    group_suffix: null
global:
  application_name: django-scraper-app
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: rishab08_work
  repository: null
  sc: git
  workspace_type: Application
